name:                flog
version:             0.1.0.0
github:              "githubuser/flog"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2026 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/flog#readme>

dependencies:
- base >= 4.7 && < 5
- wai
- warp

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - servant
  - servant-server
  - servant-auth
  - servant-auth-server
  - servant-client
  - servant-auth-client
  - persistent
  - persistent-template
  - persistent-postgresql
  - esqueleto
  - resource-pool
  - http-types
  - http-api-data
  - http-client
  - http-client-tls
  - aeson
  - text
  - extra
  - bytestring
  - mtl
  - monad-logger
  - filepath
  - directory
  - time
  - jose
  - bcrypt
  - cache
  - email-validate
  - random
  - hashable
  - brick
  - vty
  - containers
  - vty-crossplatform
  - microlens-platform

executables:
  flog-server:
    main:                Main.hs
    source-dirs:         app/backend
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flog

  flog-tui:
    main:                Main.hs
    source-dirs:         app/frontend/tui
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flog

tests:
  flog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flog
    - sandwich
